{% set version = "12.2.2" %}

package:
  name: cuda-command-line-tools
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: 5db25d4fd138013b563f9a3d1d87f7de7df1dac014fd4cccdfbb3435a5cff761

build:
  number: 0
  skip: true  # [osx]

requirements:
  run:
    - cuda-cupti-dev 12.2.142
    # There is no `cuda-gdb` support on Windows so it is skipped.
    # Also `cuda-gdb` should be supported on `ppc64le`, but is currently broken.
    # xref: https://github.com/conda-forge/cuda-command-line-tools-feedstock/issues/6
    - cuda-gdb 12.2.140       # [linux and not ppc64le]
    - cuda-nvdisasm 12.2.140
    - cuda-nvprof 12.2.142    # [not aarch64]
    - cuda-nvtx 12.2.140      # [linux]
    - cuda-sanitizer-api 12.2.140

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing the command line tools to debug CUDA applications
  description: |
    Meta-package containing the command line tools to debug CUDA applications
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
